### PR TITLE
Chore/migrate configs

### LINKED ISSUE #129: [CHORE] - Migrate Custom Configs
### What work needs to be performed?

The configurations for the tooling in this project need to be migrated to our custom global config packages.

The steps to do so will be:

- Fork and clone the repository, if you have not.
- Switch to a new branch:
  - `git checkout -b chore/migrate-configs`

## ESLint 
- Uninstall the root-level dependencies
  - `npm uninstall eslint-config-prettier eslint-plugin-import eslint-plugin-jsdoc eslint-plugin-no-only-tests eslint-plugin-prettier @typescript-eslint/eslint-plugin @typescript-eslint/parser`
- Install the eslint config
  - npm i --save-dev --save-exact @nhcarrigan/eslint-config
- Replace **all content** in the `.eslintrc.json` file with:
```json
{
  "extends": "@nhcarrigan"
}
```
- Add and commit changes
```bash
git add .
git commit -m "chore: migrate eslint"
```

## Prettier
- Install the prettier config
  - `npm i --save-dev --save-exact @nhcarrigan/prettier-config`
- Rename `.prettierrc` to `.prettierrc.json`
  - `git mv .prettierrc .prettierrc.json`
- Replace **all content** in the `.prettierrc.json` file with:
```json
"@nhcarrigan/prettier-config"
```
- Add and commit changes
```bash
git add .
git commit -m "chore: migrate prettier"
```

## TypeScript
- Install the typescript config
  - `npm i --save-dev --save-exact @nhcarrigan/typescript-config`
- Replace **all content** in the `tsconfig.json` file with:
```json
{
  "extends": "@nhcarrigan/typescript-config"
}
```
- Add and commit changes
```bash
git add .
git commit -m "chore: migrate typescript"
```

Push your changes and create a PR.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by drvnprgrmr**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #129

### CODE REVIEW

**Comment by drvnprgrmr** [comment]
@naomi-lgbt what did I do wrong? The checks are not passing.

**Comment by naomi-lgbt** [comment]
You should be using `pnpm`, not `npm`.

**Comment by drvnprgrmr** [comment]
> You should be using `pnpm`, not `npm`.

Should I delete this PR and make a new one?

**Comment by naomi-lgbt** [comment]
You should be fine to remove the `package-lock.json`, run `pnpm i`, and commit the changes to this branch.

**Comment by drvnprgrmr** [comment]
> You should be fine to remove the `package-lock.json`, run `pnpm i`, and commit the changes to this branch.

Okay, I'll do that thanks.

**Comment by drvnprgrmr** [comment]
image
Will this be an issue? Should I update prettier in package.json to v3.2?

**Comment by drvnprgrmr** [comment]
Or should I commit my changes and push?

**Comment by naomi-lgbt** [comment]
Go ahead and commit your changes.

**Comment by drvnprgrmr** [comment]
Hi @naomi-lgbt. Sorry to be a bother but the checks still aren't passing. Do you have any suggestions?

**Review by naomi-lgbt — APPROVED** [review]
This was a bit more complex than it should have been, so I pushed some commits to get everything where it needs to be.

Thanks again for all your work on this!

**Comment by drvnprgrmr** [comment]
Okay, thank you.

**Pull request merged**
